### ISSUE TITLE
How to use this plugin?

### ISSUE THREAD

**Issue by whinedo** [Wilhelm-Buechner-Hochschule/Alfresco-Wiki-Printout#1]
Hi

First of all thanks for your time.
I have a doubt when using this plugin. After installed in Alfresco, when I open a Wiki Page, I cannot see any new icon for printing. Is this plugin just formating the page when Print Page option from browser is clicked?

Thanks is advance

**Comment by eveith** [comment]
Yes, this plugin simply adds a printing CSS, but no extra button since this button would just trigger the printing dialog of the browser.

**Comment by whinedo** [comment]
Thank you very much!

**Comment by eveith** [comment]
I'm going to re-open this issue and mark it as enhancement; the additional button is just one hook away. Thanks for posting this!
