### ISSUE TITLE
Remove "Wiki Page Preview" headline

### ISSUE THREAD

**Issue by ahinrichs** [Wilhelm-Buechner-Hochschule/Alfresco-Wiki-Printout#2]
Please add

```
div.wiki-page.preview {
    display: none;
}
```

**Comment by eveith** [comment]
Fixed in 5027384

**Comment by ahinrichs** [comment]
In my report I had a typo which I corrected later. But unfortunately you copied from the version with the typo. 

It must be a div with class "wiki-page" and class "preview" (div.wiki-page.preview, note the second dot) NOT div with class "wiki-page-preview".

**Comment by eveith** [comment]
Whoops, never copy-paste tired. Fixed now, thanks. :-)
